### ISSUE TITLE
日本語がわからないと使えない (Unable to use if you do not understand Japanese)

### ISSUE THREAD

**Issue by tksugimoto** [tksugimoto/chrome-extension_open-local-folder-by-explorer#1]
Internationalization

## Target language
- [x] English

## Reference page
- [chrome.i18n - Google Chrome](https://developer.chrome.com/extensions/i18n "https://developer.chrome.com/extensions/i18n")

**Comment by mijkami** [comment]
I started a pull request for a translated version in english.

Last part of the setup (after "Right-click menu title to change") might need a rework.
The README.md might also need a rework (straight out Deepl translation).

Edit : i might start to work on a french version shortly (it's my main language after all).

**Comment by tksugimoto** [comment]
[v0.3.0](https://github.com/tksugimoto/chrome-extension_open-local-folder-by-explorer/releases/tag/v0.3.0) released

[Open local folder by explorer - Chrome ウェブストア](https://chrome.google.com/webstore/detail/open-local-folder-by-expl/ehidkllolkmedbkjbdkcgabdadcfppfg)
